#!/system/xbin/bash
# Bersihkan Layar
clear
blue='\033[34;1m'
green='\033[32;1m'
purple='\033[35;1m'
cyan='\033[36;1m'
red='\033[31;1m'
white='\033[37;1m'
yellow='\033[33;1m'
###################################################
# Team Ahs Termux
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo  $red"[#]> (Ctrl + C ) Detected, 
Trying To Exit ... "
sleep 1
echo ""
echo  $yellow"[#]> Thank You For Using My 
Tools ... "
sleep 1
echo ""
echo  $white"[#]> Mr.clay
Here ... "
read enter
exit
}
=================================================
echo $white"Author : PDT AHS TERMUX INDO"
echo $white"Team : TEAM TERMUX AHS"
echo $white"Thanks To :PDT | SEKETARIS PDT| MANUSIA TANPA JIWA | SHIFT 1 | "
echo $white"Thanks To :Indonesia Hidayah"
echo $white"thanks To : AHS CYBER"
echo $white"thanks To : JATIM BLACK HAT"
echo $white"thanks To : Blackhat Hacker Indonesia"

=================================================
echo  $yellow" 01) SHIFT AKTIVITAS"
echo  $yellow" 02) DAFTAR AHS TEAM"
echo  $yellow" 03) RULES"
echo  $yellow" 04) Top Up Ilegal FF"
echo  $yellow" 05) Webdav"
echo  $yellow" 06) Metasploit"
echo  $yellow" 07) Pulsa Gratis"
echo  $yellow" 08) Ubuntu"
echo  $yellow" 09) Youtube Dl"
echo  $yellow" 10) viSQL "
echo  $yellow" 11) multi-brute-webdav "
echo  $yellow" 12) Bajinganv6 "
echo  $yellow" 13) Tools RCT"
echo  $yellow" 14)  cc fresh Amazon Dan Untung Carding"
echo  $red" 15) Exit "
echo  $white""
read -p "[AHS TEAM]> " bro;

if [ $bro = 1 ] || [ $bro = 01 ]
then
clear
echo  $red" SHIFT AKTIVITAS "
sleep 1
SHIFT MALAM/JAM MALAM
1. A SETENGAH 12
2. 
DST 
SHIFT PAGI/JAM PAGI
1. 
2.
DST
echo  $red" T E R I N S T A L L "
exit
fi

if [ $bro = 2 ] || [ $bro = 02 ]
then
clear
echo  $red" Installing D-Tect "
sleep 1
apt-get update && apt-get upgrade
apt-get install git
apt-get install python2
git clone 
https://github.com/shawarkhanethicalhacker/D-TECT
echo  $red" T E R I N S T A L L "
exit
fi

if [ $bro = 3 ] || [ $bro = 03 ]
then
clear
echo  $red" TOP UP ILEGAL ML "
sleep 1
echo  $white " Kode :5448adq35 | Kode 5644864y36 | Kode : 3158art6455 | Kode : 90426dka656 | Kode : 6456745hkw54 | Kode :2642x655843 "
echo  $red" Masukin Kode Itu Ke Top Up Kalian ^_^"
exit
fi

if [ $bro = 4 ] || [ $bro = 04 ]
then
clear
echo  $red" TOP UP ILEGAL FF "
sleep 1
echo  $white"  Kode 5458453pr9 |Kode :260446i5m4 |Kode : 9705465d54 | Kode : 3455b623 | Kode : 84238y548 | Kode 862158t3944"
echo  $red" Masukin Kode Itu Ke Top Up Kalian ^_^"
exit
fi

if [ $bro = 5 ] || [ $bro = 05 ]
then
clear
echo  $red" Installing Webdav "
sleep 1
apt update && apt upgrade
apt install python2
pip2 install urllib3 chardet certifi idna 
requests
apt install openssl curl
pkg install libcurl
mkdir webdav
cd ~/webdav
wget https://pastebin.com/raw/HnVyQPtR -O 
webdav.py
chmod 777 webdav.py
cd ~/
echo  $red" T E R I N S T A L L "
exit
fi

if [ $bro = 06 ] || [ $bro = 6 ]
then
clear
echo  $red" Installing Metasploit "
sleep 1
apt update && apt upgrade
apt install git
apt install wget
wget
https://raw.githubusercontent.com/verluchie/termux-metasploit/master/install.sh
chmod 777 install.sh
sh install.sh
echo  $red" T E R I N S T A L L "
exit
fi

if [ $bro = 07 ] || [ $bro = 7 ]
then
clear
echo  $red" PULSA GRATIS "
sleep 1
echo  $white" Inviet Kode :2bk340dk94 | Inviet Kode 154d955b9 |Inviet Kode : 9p54k644as5 | Inviet Kode 844ipps456 | Inviet Kode : 5qdk548239 | Inviet Kode :19ip9405"
echo  $red" Masukin Kode Itu Ke Rendemm Pulsa Kalian ^_^"
exit
fi

if [ $bro = 08 ] || [ $bro = 8 ]
then
clear
echo  $red" Installing Ubuntu "
sleep 1
apt update && apt upgrade
apt install git
apt install wget
apt install proot
git clone 
https://github.com/Neo-Oli/termux-ubuntu.git
cd ~/termux-ubuntu
chmod +x ubuntu.sh
sh ubuntu.sh
echo " Fix network please wait "
sleep 1
echo "nameserver 8.8.8.8" 
>/data/data/com.termux/files/home/termux-ubuntu/ubuntu-fs/etc/$
echo  $red" T E R I N S T A L L "
exit
fi

if [ $bro = 09 ] || [ $bro = 9 ]
then
clear
echo  $red" Installing Youtube DL "
sleep 1
apt update && apt upgrade
apt install python
pip3 install mps_youtube
pip3 install youtube_dl
apt install mpv
echo " Untuk menjalankannya ketik "mpsyt" 
tanpa tanda petik "
echo  $red" T E R I N S T A L L "
exit
fi
